server:
  port: ":3000"

mode: "debug"

redis:
  protocol: "tcp"
  url: "localhost:6379"
  password: ""
  database: 0
  idle: 3
  active: 5

cors: 
  allow: 
      headers: "Content-type Access-Control-Allow-Origin Authorization Refresh-token"
  default_allow_url: "http://localhost:8080"

jwt:
  secret: "my.secret.key"
  