server:
  port: ":3000"

database: 
  user: "root"
  password: "1qaz2wsx"
  host: "localhost"
  port: "3306"
  name: "nine_tailed_fox"

mode: "debug | test | release"

redis:
  url: "localhost:6379"
  password: ""