host: staging-api.99live.live
info:
  contact:
    email: support@swagger.io
    name: Winston
  description: Golang API 專案描述
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Golang API
  version: "1.0"
paths: {}
schemes:
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
