definitions:
  models.BasketballTeam:
    properties:
      name:
        type: string
      score:
        type: integer
    type: object
  models.User:
    properties:
      account:
        type: string
      created_at:
        type: integer
      deleted_at:
        type: integer
      email:
        type: string
      id:
        type: integer
      nickname:
        type: string
      phone:
        type: string
      role_id:
        type: integer
      token:
        type: string
      updated_at:
        type: integer
    type: object
host: localhost:8887
info:
  contact:
    email: support@swagger.io
    name: Winston
  description: Golang API 專案描述
  termsOfService: http://swagger.io/terms/
  title: Golang API
  version: "1.0"
paths:
  /api/v1/redis/getset/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: RedisGetSET
      tags:
      - Redis
  /api/v1/redis/hmgetset/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: RedisHMGetSET
      tags:
      - Redis
  /api/v1/redis/listgetset:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: RedisListGetSet
      tags:
      - Redis
  /api/v1/redis/setgetset:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: RedisSetGetSet
      tags:
      - Redis
  /api/v1/redis/sortedsetgetset:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.BasketballTeam'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: RedisSortedsetGetSet
      tags:
      - Redis
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
